config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    member do
      resources :bookmarks, only: [:new, :create]
    end
  end
  resources :bookmarks, only: :destroy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def create
    # adds a movie to the current list
    @list = List.find(params[:id])
    @bookmark = Bookmark.new(bookmark_params)
    # adds the list ID to the bookmark, creating the join table relationship
    @bookmark.list = @list

    if @bookmark.save
      redirect_to :list
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list_id)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to :lists
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :img_url, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="form-container">
  <h1>Add movie to <%= @list.name %></h1>
  <%= simple_form_for @bookmark do |f|%>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <div class="d-flex justify-content-between">
      <%= f.submit 'Add movie', class: 'btn btn-warning' %>
      <%= link_to 'Cancel', list_path(@list), class: 'btn btn-danger'  %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <nav class='navbar d-flex justify-content-center align-items-center'>
      <a href="/lists" style="text-decoration: none; color: black;"><h3 > Movielists </h3></a>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1535016120720-40c646be5580?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bW92aWV8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60);">
  <div class="container">
    <h1>Movie List Maker</h1>
    <p>Create movie lists and share them with your friends!</p>
    <% if @lists.any? %>
      <%= link_to 'Add List', new_list_path, class: 'btn btn-success' %>
    <% else %>
       <%= link_to 'Get Started', new_list_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>
<h2 class="m-3 p-2 border-bottom">Lists</h2>
<div class="d-flex justify-content-start">
  <% @lists.each do |list| %>
    <div class="card-category m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key, :width => 800, :height => 600, :crop => :fill) : image_path(list.img_url) %>)">
      <%= list.name %>
      <%= link_to '', list_path(list), class: 'card-category-link' %>
      <div class="d-flex align-items-center number-of-movies">
        <i class="fas fa-video"></i>
        <p > <%= list.movies.count %> </p>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="form-container">
  <h1>New List</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :img_url %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-warning'%>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : image_path(@list.img_url) %>);">
  <div class="container">
    <h1> <%= @list.name %> </h1>
    <p>Press the round + to add movie to list!</p>
  </div>
</div>


<div class="d-flex flex-wrap justify-content-start align-items-start">
    <% @list.bookmarks.each do |bookmark| %>
       <div class="card-product m-2 relative align-items-start">
          <img src= <%= bookmark.movie.poster_url %> />
          <div class="card-product-infos flex-grow-1">
            <h2> <%= bookmark.movie.title %> </h2>
            <p><strong>Rating: </strong> <%= bookmark.movie.rating %> </p>
            <p> <%= bookmark.comment %> </p>
          </div>
          <%= link_to bookmark_path(bookmark), method: :delete, class: 'delete-btn' do %>
            <i class="fas fa-backspace"></i>
          <% end %>
        </div>
    <% end %>
    <div class="card-add-container relative">
       <div class="card-add m-2 d-flex justify-content-center align-items-center">

          <%= link_to new_bookmark_path do %>
            <i class="fas fa-plus " style="font-size: 40px;"> </i>
          <% end %>
        </div>
    </div>
</div>